services:
    app:
        env_file:
            - .env
        restart: always
        image: svelte-docker
        build:
            context: .
            dockerfile: DOCKERFILE
            target: run
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Root1234!
            MYSQL_DATABASE: tvn_order
            MYSQL_USER: admin
            MYSQL_PASSWORD: Admin1234!
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3307:3306
volumes:
    db_data: {}
