services:
  app:
    container_name: webpage_tvn_order
    env_file:
      - .env
    restart: always
    image: svelte-docker
    build:
      context: .
      dockerfile: DOCKERFILE
      target: run
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: mysql_tvn_order
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  db_data: {}
