# docker-compose.yml

services:
  external:
    container_name: tvn_order
    # The name of the image that will be created when building this container
    image: tvn_order:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Zurich
    # Points to a file with the sensitive environment variables
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
